[UT-855] Financing tab
Instamotion/im-components pull request #229
Opened 2021-04-14 14:13 UTC by rafaelspiljak

2021-04-22 07:27 UTC, jogamod approved these changes

2021-04-22 07:42 UTC, AntonTretiak requested changes

2021-04-22 07:42 UTC, AntonTretiak commented on packages/FinancingTab/src/ContentBoxRadio/ContentBoxRadioButtonGroup.tsx
> +              {USP_MAPPINGS[String(item.value) === 'classic' ? 'classic' : 'easygo'].map(
probably enum would be better?

2021-04-22 07:42 UTC, AntonTretiak commented on packages/FinancingTab/src/ContentBoxRadio/CurrencyInput.tsx
> +import React, { useState } from 'react';
this one probably should be moved to @im-ui/input as a new type of input.
Also make sure that input are up to date with our designs:  https://www.figma.com/file/pyKoaEQvDB9s5IJq4sffVN/styleguide-instamotion?node-id=429%3A397

2021-04-22 07:42 UTC, AntonTretiak commented on packages/FinancingTab/src/ContentBoxRadio/RadioButton.tsx
> +import React from 'react';
this one could be moved to Radio lib too

2021-04-22 07:42 UTC, AntonTretiak commented on packages/FinancingTab/src/FinancingTab.tsx
> +interface Offer {
Probably if we are going to use GQL interfaces it make sense to look deeper if we can import our GQL types here. Especially if we are going to add calculation to lib too, but it probably should be discussed with Danijel

2021-04-22 07:42 UTC, AntonTretiak commented on packages/FinancingTab/src/FinancingTab.tsx
> +            Mehr zu Finanzierungsarten
In lib's we also have translations. Make sure we are using it. Check `@im-ui/footer` as a guid how to do it.

2021-04-22 07:42 UTC, AntonTretiak commented on packages/FinancingTab/src/MonthlyRateChooser.tsx
> +  return items.filter((item: IMonthsSelection) => item.disabled !== true);
`return items.filter((item: IMonthsSelection) => !item.disabled);` - would do the same.

2021-04-22 07:42 UTC, AntonTretiak commented on packages/FinancingTab/src/MonthlyRateChooser.tsx
> +    onChange(Number(e.target.value));
`onChange(Number(value));` - should be in this case, otherwise don't see the reason to do `e: { target: { value: string } }`

2021-04-22 07:42 UTC, AntonTretiak commented on packages/FinancingTab/src/assets/CheckIcon.tsx
> +const CheckIcon: React.FC = () => (
could be moved to icon lib

2021-04-22 07:42 UTC, AntonTretiak commented on packages/buttonToggle/src/buttonToggle.tsx
> +      background-color: #e5e5e5;
also have it in theme lib

2021-04-22 07:42 UTC, AntonTretiak commented on packages/radioButton/src/radioButton.tsx
> +  background-color: #f7f7f7;
colours from lib

2021-04-22 07:42 UTC, AntonTretiak commented on packages/radioButton/src/radioButton.tsx
> +    background-color: #76dfbf;
colour

2021-04-22 07:55 UTC, karlosintic commented on packages/FinancingTab/src/ContentBoxRadio/CurrencyInput.tsx
> +import React, { useState } from 'react';
It makes sense to move this to the input package. It is already in line with our new designs - I'll ask Mickael to create separate for moving this into @im-ui/input.

2021-04-22 07:56 UTC, karlosintic commented on packages/FinancingTab/src/ContentBoxRadio/RadioButton.tsx
> +import React from 'react';
Same as above.

2021-04-22 07:59 UTC, karlosintic commented on packages/FinancingTab/src/FinancingTab.tsx
> +interface Offer {
We can hop on a call today and discuss how we should approach this. I would leave this as it is for now, only to test if current implementation is working.

2021-04-22 08:49 UTC, karlosintic commented on packages/radioButton/src/radioButton.tsx
> +  background-color: #f7f7f7;
This one is not in the lib, but I can add it.

2021-04-22 08:49 UTC, karlosintic commented on packages/radioButton/src/radioButton.tsx
> +    background-color: #76dfbf;
This one is also not in the lib, but it can be added.

2021-04-22 09:03 UTC, karlosintic commented on packages/FinancingTab/src/ContentBoxRadio/ContentBoxRadioButtonGroup.tsx
> +              {USP_MAPPINGS[String(item.value) === 'classic' ? 'classic' : 'easygo'].map(
`USP_MAPPINGS` is enum, and this line gets a list from enum based on passed value.

2021-04-22 09:19 UTC, AntonTretiak commented on packages/radioButton/src/radioButton.tsx
> +  background-color: #f7f7f7;
I guess we should as soon as it appear in design

2021-04-22 09:19 UTC, AntonTretiak commented on packages/radioButton/src/radioButton.tsx
> +    background-color: #76dfbf;
same

2021-04-22 09:35 UTC, karlosintic commented on packages/radioButton/src/radioButton.tsx
> +  background-color: #f7f7f7;
PR: #238

2021-04-22 09:35 UTC, karlosintic commented on packages/radioButton/src/radioButton.tsx
> +    background-color: #76dfbf;
PR: #238

2021-04-22 10:11 UTC, karlosintic commented on packages/buttonToggle/src/buttonToggle.tsx
> +      background-color: #e5e5e5;
Replaced.

2021-04-22 10:11 UTC, karlosintic commented on packages/FinancingTab/src/assets/CheckIcon.tsx
> +const CheckIcon: React.FC = () => (
PR: #239

2021-04-22 13:35 UTC, karlosintic commented on packages/FinancingTab/src/MonthlyRateChooser.tsx
> +  return items.filter((item: IMonthsSelection) => item.disabled !== true);
Implemented as per suggestion.

2021-04-23 07:44 UTC, karlosintic commented on packages/FinancingTab/src/ContentBoxRadio/RadioButton.tsx
> +import React from 'react';
Actually, this kind of radio button is only used here in the ContentBox, so there is no need to move it to Radio lib.

2021-04-23 14:05 UTC, karlosintic commented on packages/FinancingTab/src/ContentBoxRadio/CurrencyInput.tsx
> +import React, { useState } from 'react';
Done! Related PR: #240

2021-04-23 14:19 UTC, AntonTretiak requested changes

2021-04-23 14:19 UTC, AntonTretiak commented on packages/FinancingTab/src/FinancingTab.tsx
> +  const ToggleWrapper = styled.div`
probably should be outside component. Also if it's too much styles, could be in a separate file (optional).

2021-04-23 14:19 UTC, AntonTretiak commented on packages/FinancingTab/src/FinancingTab.tsx
> +              selected === 'easygo'
`props.onChangeWithBalloonRate(selected === 'easygo')` seems more accuracy

2021-04-23 14:19 UTC, AntonTretiak commented on packages/FinancingTab/src/FinancingTab.tsx
> +  const CalculatorPane = styled(Col as any)`
all styles out of the component.

2021-04-23 14:19 UTC, AntonTretiak commented on packages/FinancingTab/src/FinancingTab.tsx
> +          <StyledLink onClick={props.openFinancingPackagesInfoModal}>
Also regarding `props` probably make sense to make this as in other places as destructuring with default values like:
`const Calculator = ({openFinancingPackagesInfoModal, state, carPrice ...}: CalculatorProps) =>

2021-04-23 14:19 UTC, AntonTretiak commented on packages/FinancingTab/utils/locales.ts
> +  'default.financing_tab.more_financing_info': 'Mehr zu Finanzierungsarten',
please add README file with list of translation expected

2021-04-23 14:19 UTC, AntonTretiak commented on packages/FinancingTab/src/ContentBoxRadio/ContentBoxRadioButtonGroup.tsx
> +      'Niedrige monatliche Raten​',
also make sure if we need to translate this too or not. Clarify with Mickael probably

2021-04-26 07:51 UTC, karlosintic commented on packages/FinancingTab/src/ContentBoxRadio/ContentBoxRadioButtonGroup.tsx
> +      'Niedrige monatliche Raten​',
Done.

2021-04-26 07:51 UTC, karlosintic commented on packages/FinancingTab/utils/locales.ts
> +  'default.financing_tab.more_financing_info': 'Mehr zu Finanzierungsarten',
Done.

2021-04-26 07:52 UTC, karlosintic commented on packages/FinancingTab/src/FinancingTab.tsx
> +  const CalculatorPane = styled(Col as any)`
Done.

2021-04-26 07:55 UTC, karlosintic commented on packages/FinancingTab/src/FinancingTab.tsx
> +              selected === 'easygo'
Could you elaborate a bit here?

2021-04-26 10:01 UTC, AntonTretiak approved these changes

2021-04-26 10:34 UTC, merged